### ISSUE TITLE
Render delay when begain  a game

### ISSUE THREAD

**Issue by 1078559858** [drawapp8/gameui-for-pixi-js#2]
create a new game use gameui_for_pixi_js,
if your first gameUI is maked by hola studio,then will not appeared in the screen(win7\iphone5s\iphone6s\android).
you must click the screen to flash it ,then appeared.

win7\iphone\android
chrome\QQ\weixin

**Comment by 1078559858** [comment]
pixi-cantk.js

move "wm.loadAssets();" to  between "this.openWindowOrg(name, onClose, closeCurrent, initData, options);" and "var win = wm.find(name);" .
can soleve this problem.
but i don't know why, i'm thinking.

and if in QQ or weixin in android open the game.
then will not work.

**Comment by 1078559858** [comment]
// setTimeout(function() {
	// 	ResLoader.notifyLoadProgress();
	// }, 1);

this should change to ：

ResLoader.notifyLoadProgress(); 

why used setTimeout function? i think not;

**Comment by drawapp8** [comment]
I updated the code, please recheck it, thanks.
