### ISSUE TITLE
not found type of "ui-spine"

### ISSUE THREAD

**Issue by 1078559858** [drawapp8/gameui-for-pixi-js#3]
add a ui-element of spine,
loaded it ,and  there is a error :not found type ui-spine, create ui-unkown instead.

在编辑器中添加一个spine组件，
加载scene后，弹出一个错误：无法找到ui-spine

**Comment by drawapp8** [comment]
考虑到UI界面一般不需要spine和dragones，所以它们放在单独的包里面。如果你需要可以自己引入进来：
调试版：http://studio.holaverse.cn/cantk/js/cantk-debug-spine.js
发布版：http://studio.holaverse.cn/cantk/js/cantk-spine.js

**Comment by 1078559858** [comment]
谢谢！
原来，在“示例中心”“Hola Studio示例组件”中下载对应的就可以了。
赞！
